# Generated by Django 5.1.7 on 2025-04-23 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('less_than_year', models.BooleanField(default=False, verbose_name='Опыт меньше года')),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True, verbose_name='Опыт работы (лет)')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ставка в час (₽)')),
                ('monthly_rate', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ставка в месяц (₽)')),
                ('description', models.TextField(verbose_name='Описание опыта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sphere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sphere', verbose_name='Категория')),
                ('sphere_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.spheretype', verbose_name='Подкатегория')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to=settings.AUTH_USER_MODEL, verbose_name='Фрилансер')),
            ],
            options={
                'verbose_name': 'Портфолио',
                'verbose_name_plural': 'Портфолио',
            },
        ),
    ]
