# Generated by Django 5.1.7 on 2025-04-25 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_orderfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Почему именно вы')),
                ('term', models.PositiveIntegerField(verbose_name='Срок исполнения (дни)')),
                ('responser_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ваша цена (₽)')),
                ('status', models.CharField(choices=[('Pending', 'Ожидает'), ('Accepted', 'Принят'), ('Rejected', 'Отклонён')], default='Pending', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='core.order', verbose_name='Заказ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to=settings.AUTH_USER_MODEL, verbose_name='Фрилансер')),
            ],
            options={
                'verbose_name': 'Отклик',
                'verbose_name_plural': 'Отклики',
                'unique_together': {('order', 'user')},
            },
        ),
    ]
