# Generated by Django 5.1.7 on 2025-04-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reason_of_cancel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
