# Generated by Django 5.1.7 on 2025-04-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_order_reason_of_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
