# Generated by Django 5.1.7 on 2025-05-12 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('like', '👍 Лайк'), ('dislike', '👎 Дизлайк')], max_length=7)),
                ('comment', models.TextField(blank=True, help_text='Текст отзыва')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(help_text='Клиент, который оставил отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(help_text='Фрилансер, которому оставлен отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='Заказ, по которому оставлен отзыв', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.order')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'unique_together': {('order', 'client')},
            },
        ),
    ]
