# Generated by Django 5.1.7 on 2025-05-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Текущий баланс пользователя', max_digits=12, verbose_name='Баланс'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
