# Generated by Django 5.1.7 on 2025-06-05 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_review_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Фрилансер')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Приглашение на заказ',
                'verbose_name_plural': 'Приглашения на заказы',
                'unique_together': {('order', 'freelancer')},
            },
        ),
    ]
